name: google_sign_in_web
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android, iOS and Web.
publish_to: none
version: 0.10.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: google_sign_in
    platforms:
      web:
        pluginClass: GoogleSignInPlugin
        fileName: google_sign_in_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # google_sign_in_platform_interface: ^2.0.0
  google_sign_in_platform_interface:
    git:
      url: git://github.com/rosputniy/plugins.git
      path: packages/google_sign_in/google_sign_in_platform_interface
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
